### ISSUE TITLE
Replace return type annotation `:` with `->` 

### ISSUE THREAD

**Issue by baszalmstra** [mun-lang/mun#105]
We would benefit from staying close to Rust syntax, however, currently return type annotations are written like:

```
fn foo(): int {
}
```

we would like to replace this syntax with this:

```
fn foo() -> int {
}
```

to be closer to Rust.

**Good first issue process:**

- [ ] [read our contributing guidelines](https://github.com/mun-lang/mun/blob/master/CONTRIBUTING.md)
- [ ] claim this issue (assign yourself or comment below)
- [ ] implement the feature and start a Pull Request with in the description: closes #105. 

If this is your first PR, welcome 🎉 😄

**Comment by hzqd** [comment]
What are the obvious benefits of bearing a resemblance to Rust?
The `:` syntax to declare a function return type is the same as many programming languages such as Kotlin, Scala, Swift, etc. Changing it to `->` is no real benefit, but type one more character.

**Comment by baszalmstra** [comment]
There is no obvious benefit here. The main reason for doing this is that most of our users are coming from Rust at this point and its an inconvenience to have this small difference between the two languages.

**Comment by jakbyte** [comment]
I think I've gotten this working. Should I update the tests accordingly?

**Comment by jakbyte** [comment]
Never mind, looks like I'll have to to commit.

**Comment by baszalmstra** [comment]
Yes all test should be updated accordingly. Thats indeed probably a lot of them. Once you run all tests once you can use:

cargo insta review

To validate the new outputs

**Comment by jakbyte** [comment]
Okay, it's done! I'll open a pull request soon.

**Comment by jakbyte** [comment]
The pull request is #123.
