### ISSUE TITLE
feat: add type aliases

### ISSUE THREAD

**Issue by Wodann** [mun-lang/mun#110]
We want to introduce type aliases, as follows:

```rust
type Typename = OtherTypeName;
```

In large, this change builds on existing architecture, but it will require work in several places of our stack:
- [ ] lexer: add the `type` keyword ([src](https://github.com/mun-lang/mun/blob/master/crates/mun_syntax/src/grammar.ron), [example](https://github.com/rust-analyzer/rust-analyzer/blob/363718ba42d1eb906577a0a03c14248a0962a06a/crates/ra_syntax/src/grammar.ron#L90))
- [ ] parsing: add parsing of `type TypeName = OtherTypeName` ([example#1](https://github.com/rust-analyzer/rust-analyzer/blob/363718ba42d1eb906577a0a03c14248a0962a06a/crates/ra_syntax/src/grammar.ron#L139), [example#2](https://github.com/rust-analyzer/rust-analyzer/blob/363718ba42d1eb906577a0a03c14248a0962a06a/crates/ra_parser/src/grammar/items.rs#L336))
- [ ] hir: add type aliases as type definition ([src](https://github.com/mun-lang/mun/tree/master/crates/mun_hir/src))
- [ ] tests: add test for all of the above stages

**Good first issue process:**

- [ ] [read our contributing guidelines](https://github.com/mun-lang/mun/blob/master/CONTRIBUTING.md)
- [ ] claim this issue (assign yourself or comment below)
- [ ] implement the feature and start a Pull Request with in the description: closes #110. 

If this is your first PR, welcome 🎉 😄

**Comment by fominok** [comment]
Hey,
I think that this issue will make more sense if generics feature lands. Or are there any use cases in current language state?

**Comment by baszalmstra** [comment]
Yes there was previously a case where this was needed. But that was no longer the case so this has much lower priority.

**Comment by sinato** [comment]
I have a question about mun-lang syntax. Should type aliases be definable in a block?
For example, should Example 2 work the same as Example 1?
Example1:

```rust
type OtherTypename = i32;
type Typename = OtherTypename;
fn main() {
    let a: Typename = 10
}
```

Example2:

```rust
type OtherTypeName = i32;
fn main() {
    type Typename = OtherTypeName;  // <- Does mun-lang expect this?
    let a: Typename = 10;
}
```

**Comment by Wodann** [comment]
Yes, [Rust supports this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bda07dc4a1e5bbaee0a2d67e9c9300e6) and my expectation for Mun was to mimick this.

**Comment by sinato** [comment]
@Wodann
Hi, may I create a PR to support only [Example1](https://github.com/mun-lang/mun/issues/110#issuecomment-671688006)?

rust-analyzer does not yet support Example2.
> The current code in rust-analyzer just completely ignores local items and builds a Resolver instance for top-level scope.

https://github.com/rust-analyzer/rust-analyzer/issues/1165
I think it would be better to wait a little longer for the implementation of Example 2 to reuse their consideration and implementation.
