### ISSUE TITLE
Codegen Option::unwrap() panic during build

### ISSUE THREAD

**Issue by jakbyte** [mun-lang/mun#133]
The following script:

```rust
fn do_the_things(n: int) -> int {
    n + 7
}

pub fn main() {
    do_the_things(3);
}
```

causes this panic:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/mun_codegen/src/code_gen/symbols.rs:146:9
```

It compiles properly if `do_the_things` is `pub`.

It looks like it can't find the return type in the module for some reason.

**Comment by baszalmstra** [comment]
Thanks for reporting, I will take a look when I have the time!

**Comment by Wodann** [comment]
I am in the process of working on the fix. It involves a small refactor to include symbol generation in all codegen tests, which I will wrap up tomorrow.
