### ISSUE TITLE
refactor(abi): move privacy and name from `FunctionSignature` to `FunctionInfo`

### ISSUE THREAD

**Issue by baszalmstra** [mun-lang/mun#146]
Current the `FunctionSignature` contains this information. We need to move that to `FunctionInfo`.

**Good first issue process:**

- [ ] [read our contributing guidelines](https://github.com/mun-lang/mun/blob/master/CONTRIBUTING.md)
- [ ] claim this issue (assign yourself or comment below)
- [ ] implement the feature and start a Pull Request with in the description: closes #146. 

If this is your first PR, welcome 🎉 😄

**Comment by attliaLin** [comment]
I'd like to take it.

**Comment by baszalmstra** [comment]
Ah thats super good to hear! Welcome :)

However, I forgot to update this issue, we've already done this in https://github.com/mun-lang/mun/pull/166 :(
