### ISSUE TITLE
Write test for C++ bindings

### ISSUE THREAD

**Issue by baszalmstra** [mun-lang/mun#150]
Currently, our C++ bindings have no tests to validate that they function as they should.

This issue is about adding those tests.

**Comment by baszalmstra** [comment]
An implementation is underway in: https://github.com/mun-lang/runtime-ffi/tree/feature/interop-c

**Comment by Wodann** [comment]
https://github.com/mun-lang/runtime-ffi/commit/b824a88c0d878850eea60839ade621dab1f70b56
