### ISSUE TITLE
Remove deprecated `Failure` crate

### ISSUE THREAD

**Issue by baszalmstra** [mun-lang/mun#177]
We use the `Failure` crate throughout the Mun codebase but it has been deprecated. It would be a good idea to replace it.

Suggested alternatives to use in places where we do use `Failure` (which is not really a lot) are:

* [anyhow](https://github.com/dtolnay/anyhow) as a replacement for `failure::Error`
* ~~[displaydoc](https://github.com/yaahc/displaydoc) seems like a good replacement for `#[derive(Fail)]`~~
* [thiserror](https://github.com/dtolnay/thiserror) as a replacement for `#[derive(Fail)]`

**Good first issue process:**

- [ ] [read our contributing guidelines](https://github.com/mun-lang/mun/blob/master/CONTRIBUTING.md)
- [ ] claim this issue (assign yourself or comment below)
- [ ] implement the feature and start a Pull Request with in the description: closes #177. 

If this is your first PR, welcome 🎉 😄

**Comment by Wodann** [comment]
I came across this [article](https://nick.groenen.me/posts/rust-error-handling) about error handling in Rust. They combine anyhow with thiserror (that does the same as `derive(Failure)` except that they are by the same maintainer. I like their approach

**Comment by baszalmstra** [comment]
I actually preferred `displaydoc` over `thiserror` (although you still need `thiserror` when using `displaydoc`) because I really like that it also immediately is added as a comment.

However! reading the article linked by @Wodann also shows examples where you might not want the comment to say the same thing as the error message. So just using `thiserror` indeed seems like a better option.

**Comment by parasyte** [comment]
I can take this one. Having some trouble with `fmt` check, but it's failing on master, too: https://github.com/mun-lang/mun/runs/741643566
