### ISSUE TITLE
State of 0.1.0 Binaries?

### ISSUE THREAD

**Issue by stevedonovan** [mun-lang/mun#185]
After unpacking the linux binaries, the Fibonacci example cannot compile.

This is a known thing?  Any chance of more uptodate snapshots?

**Comment by baszalmstra** [comment]
Hey @stevedonovan! We are aware, the example was horribly outdated with the progress we made with the compiler. But good news, we _just_ release v0.2 and also updated all corresponding examples so now everything should work again. :)
