### ISSUE TITLE
Fibonacci example doesn't compile because of ; in line 3

### ISSUE THREAD

**Issue by Aloso** [mun-lang/mun#193]
The semicolon in line 3 of [this example](https://docs.mun-lang.org/ch01-02-hello-fibonacci.html) prevents it from compiling:

```rust
pub fn fibonacci_n() -> i64 {
    let n = arg();
    fibonacci(n);
}

fn arg() -> i64 {
    5
}

fn fibonacci(n: i64) -> i64 {
    if n <= 1 {
        n
    } else {
        fibonacci(n - 1) + fibonacci(n - 2)
    }
}
```

P.S. sorry for reporting this in the wrong repo!

**Comment by baszalmstra** [comment]
I think this PR fixes that, just needs to propagate through CI: https://github.com/mun-lang/mun/pull/192

**Comment by baszalmstra** [comment]
The fix is online :), thanks for reporting!
