### ISSUE TITLE
Test Mun examples in the book

### ISSUE THREAD

**Issue by baszalmstra** [mun-lang/mun#209]
The book contains a lot of useful Mun code examples. We incorporated the Mun book into the main repository to be able to test all these examples while we develop the language. This hopefully ensures that the book stays up to date with the features we develop.

However, currently, we are not yet testing all these examples. To do so we probably need to create [a plugin for mdbook](https://github.com/rust-lang/mdBook#3rd-party-plugins).

**Good first issue process:**

- [x] [read our contributing guidelines](https://github.com/mun-lang/mun/blob/master/CONTRIBUTING.md)
- [x] claim this issue (assign yourself or comment below)
- [ ] implement the feature and start a Pull Request with in the description: closes #209 . 

If this is your first PR, welcome 🎉 😄

**Comment by legendiguess** [comment]
I would like to contribute to this issue 👀
