### ISSUE TITLE
Panic in `mun build` in certain situations with external functions

### ISSUE THREAD

**Issue by Imberflur** [mun-lang/mun#222]
```
> mun build test.mun
mun: /usr/lib/libtinfo.so.5: no version information available (required by mun)
thread 'main' panicked at 'missing function value for hir function: 'foo'', <::std::macros::panic macros>:5:6
```
Looks like [this panic](https://github.com/mun-lang/mun/blob/9f4c8d7ea660bca65d6468d3df19295f24633c41/crates/mun_codegen/src/ir/body.rs#L1047)

If either of the commented lines are used the panic does not occur.
```rs
extern fn foo();
extern fn bar();

pub fn two() {
    bar();
    //foo(); // works with this
    one(); // no effect with or without this
}

//pub fn fn_one() { // works with this
fn one() {
    bar();
    foo();
}
```

could be related to https://github.com/mun-lang/mun/pull/221?

**Comment by baszalmstra** [comment]
I just added your example as test case:
```rust
#[test]
fn issue_222() {
    test_snapshot(r#"
    extern fn foo();
    extern fn bar();

    pub fn two() {
        bar();
        //foo(); // works with this
        one(); // no effect with or without this
    }

    //pub fn fn_one() { // works with this
    fn one() {
        bar();
        foo();
    }
    "#)
}
``` 

in https://github.com/mun-lang/mun/blob/master/crates/mun_codegen/src/test.rs . I can verify that the fix in #221 fixes this issue. It fails on master.

**Comment by baszalmstra** [comment]
I can confirm that #221 fixed the issue. We'll backport this to v0.2 and publish a new version.

**Comment by baszalmstra** [comment]
#221 fixed this issue, it has also been backported to the [`release/v0.2`](https://github.com/mun-lang/mun/commit/432aa9122dee7997e4f0b20676a31cb667fc1c10) branch.
