### ISSUE TITLE
Generated llvm ir triggers llvm assertions

### ISSUE THREAD

**Issue by jDomantas** [mun-lang/mun#227]
So I accidentally compiled my llvm with assertions enabled, and now trying to run mun tests aborts with llvm assertion failure:

```
>  cargo test -p mun_codegen -- function_arguments
    Finished test [unoptimized + debuginfo] target(s) in 0.34s
     Running target\debug\deps\mun_codegen-d51557810a1e1457.exe

running 1 test
Assertion failed: V[I]->getType() == T->getTypeAtIndex(I) && "Initializer for composite element doesn't match!", file ###\lib\IR\Constants.cpp, line 951
error: test failed, to rerun pass '-p mun_codegen --lib'

Caused by:
  process didn't exit successfully: `###\target\debug\deps\mun_codegen-d51557810a1e1457.exe function_arguments` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

Looking at the [ir snapshot](https://github.com/mun-lang/mun/blob/ec0c49ddbd70acf14cf9c8ce49d9709bbd46d524/crates/mun_codegen/src/snapshots/test__function_arguments.snap) my suspicion is that type info initializer does not match the declared type `MunTypeInfo`:

```
%struct.MunTypeInfo = type { [16 x i8], i8*, i32, i8, i8 }
                                        ^^^ declared as i8*
...

@"type_info::<core::i32>" = private unnamed_addr constant %struct.MunTypeInfo { [16 x i8] c"\17yzt\19\D62\17\D25\95C\17\88[\FA", [10 x i8]* @"type_info::<core::i32>::name", i32 32, i8 4, i8 0 }
                                                                                                                                 ^^^^^^^^^^ initializer uses [10 x i8]*

```

**Comment by baszalmstra** [comment]
Ah yes I was afraid that would bite us in the ass at some point. :smile: 

We use an old C trick here. I'll take a look at it to see if I can do it correctly.

**Comment by baszalmstra** [comment]
It took me quite a while (also due to compiling LLVM..) but I fixed all assertions that are thrown when running the tests (#233)

Your hunch was correct in that a `[16 x i8]` is not the same as an `i8*`. Without assertions this works fine but with assertions LLVM complains. I introduced some constraints that ensure that we properly cast these values.
