### ISSUE TITLE
Implement `mun new` and `mun init`

### ISSUE THREAD

**Issue by baszalmstra** [mun-lang/mun#237]
Now that [projects have landed](#223) it would be good if we can create a barebones project by invoking `mun new` or `mun init` similar to [`cargo new`](https://doc.rust-lang.org/cargo/commands/cargo-new.html) and [`cargo init`](https://doc.rust-lang.org/cargo/commands/cargo-init.html).

**Good first issue process:**

- [ ] [read our contributing guidelines](https://github.com/mun-lang/mun/blob/master/CONTRIBUTING.md)
- [ ] claim this issue (assign yourself or comment below)
- [ ] implement the feature and start a Pull Request with in the description: closes #237. 

If this is your first PR, welcome 🎉 😄

Related to #223

**Comment by ethanboxx** [comment]
Hi, I would like to try doing this. It would be my first PR on Mun.

**Comment by Wodann** [comment]
Welcome! I've assigned the issue to you 🙂 

If you need any help, feel free to reach out to us here or on our Discord!

**Comment by Wodann** [comment]
Thank you for your help @ethanboxx! A very good collaboration with quick back and forth on improvements. We hope that this is the first of many more PRs to come! 🎉
