### ISSUE TITLE
Pin Rust version

### ISSUE THREAD

**Issue by baszalmstra** [mun-lang/mun#247]
Everytime Rust releases a new version our builds break. This happens because new lints are added for instance. We want to keep up to date with the latest Rust version but its anoying that if someone submits a PR CI might fail because a new Rust version was just released.

I propose we do something similar to `vector`, they store [a file](https://github.com/timberio/vector/blob/master/rust-toolchain) that stores which version of Rust CI should use. Its trivial to bump Mun to a new Rust version by creating a new PR that modifies the contents of that file together with fixing any issues that may be caused by the version bump.

To implement this we just need to modify our CI workflow to read the version to use from a file.

**Good first issue process:**

- [x] [read our contributing guidelines](https://github.com/mun-lang/mun/blob/master/CONTRIBUTING.md)
- [x] claim this issue (assign yourself or comment below)
- [ ] implement the feature and start a Pull Request with in the description: closes #247 . 

If this is your first PR, welcome 🎉 😄

**Comment by sinato** [comment]
Hi, I would like to try doing this.

**Comment by Wodann** [comment]
Excellent! As always, please let @baszalmstra  or me know if you have any questions.
