### ISSUE TITLE
Arch Linux build info out of date

### ISSUE THREAD

**Issue by baszalmstra** [mun-lang/mun#259]
With  #254 the build instructions for ArchLinux are out of date (Since we require LLVM8 now). We should update these, but it also requires that we create and upload a package for lld8.

**Comment by wackbyte** [comment]
Unfortunately, it looks like the `llvm8` AUR package that already exists [doesn't build without a workaround](https://aur.archlinux.org/packages/llvm8#comment-745687). I can't make an `lld8` package without that package being fixed.

**Comment by baszalmstra** [comment]
@wackbyte I noticed there have been some changes to the `llvm8` AUR package. Does this fix the issues you were having before?

**Comment by baszalmstra** [comment]
@Wodann Im thinking about dropping support for building Arch builds in our Readme. We should at some point describe in more detail how to build LLVM for various platforms ([similar to Zig](https://github.com/ziglang/zig/wiki/How-to-build-LLVM,-libclang,-and-liblld-from-source)) but since its hard for us to test on this platform I feel like we cant really actively support this. 

Once the next inkwell release lands (beta1), we should be able to build a "standalone" binary that should be usable on Arch. This should support most use-cases. If someone does want to build from source we should document a common way of building LLVM, Clang and LLD from source ([something like this](https://github.com/ziglang/zig/wiki/Building-Static-Zig-on-FreeBSD)). 

WDYT?

**Comment by Wodann** [comment]
I agree with that. If we can provide adequate documentation for people to support Mun on their respective systems that'd strike a better balance.

**Comment by baszalmstra** [comment]
👍 Ill write something up in the development section of the book.
