### ISSUE TITLE
Docs/Book appears to be a 404

### ISSUE THREAD

**Issue by shanehandley** [mun-lang/mun#277]
Hi, I'm interested in reading up on mun, however links from the website to [https://docs.mun-lang.org/](https://docs.mun-lang.org/) are returning an error page. 

(I've found some docs via https://release-v0-2.docs.mun-lang.org/ but not certain if that's up to date)

Cheers.

**Comment by baszalmstra** [comment]
Looks like our netlify build is failing because it cant find the new Mun plugin introduced in #263

**Comment by baszalmstra** [comment]
@legendiguess How do you make sure the plugin is available when building the book?

**Comment by Wodann** [comment]
@shanehandley thanks for reporting the issue.

https://release-v0-2.docs.mun-lang.org/ is useful for our latest public release, but not for our master branch.

[This deploy](https://5f5cef1007eddb0007c7d5da--docs-mun-lang.netlify.app/) should be a more up-to-date version of the Mun book that you can use until we fix the build issue.

**Comment by baszalmstra** [comment]
Solved by #278
