### ISSUE TITLE
Using Mun in a threaded environment

### ISSUE THREAD

**Issue by baszalmstra** [mun-lang/mun#299]
The `mun_runtime::Runtime` is not `Sync` nor `Send` since the `RuntimeBuilder::spawn` function returns a `Rc<RefCell<Runtime>>`. This makes it hard to use in other programs that make use of threads. The reason we wrap the `Runtime` in an `Rc` is because the runtime (or better yet, the memory model) is not thread safe. Wrapping the `Runtime` in a mutex will also not work because the memory model is shared between other structs (like `StructRef`). Sending the `Runtime` to a thread and doing modifications while also accessing a `StructRef` from another thread will cause threading issues. 

We've already talked about this a lot. We currently have no proper plan to support multithreading. However, our current solution is also not very ergonomic. I propose we implement a blocking solution that still doesnt do multithreading of the runtime but does allow the runtime and derived data to be shared across threads. In a later version we can then add proper multithreading hopefully using the same API we design now.

A straighforward solution is to wrap all memory modifying operations inside a mutex. This will block any operation performed by other threads but will enable the use of the Runtime and derived data to be send to different threads.

Curious to your thoughts!

**Comment by baszalmstra** [comment]
Looking at it closer, the `StructRef` is already safe because it is tied to the lifetime of the runtime. If we ensure that you can only use a rooted struct by first converting it to a `StructRef` (the `RootedStruct::as_ref`), which is again tied to the runtime, we can make the runtime `Send`. The `as_ref` method is currently unsafe. I would prefer to have an API like:

```
let rooted_struct:RootedStruct = // ...
let ref:StructRef<'r> = runtime.get_ref(rooted_struct).unwrap();
invoke_fn!("main", ref)
```

This involves making sure that the `get_ref` method can be safely called. WDYT @Wodann?

**Comment by Wodann** [comment]
IIRC, the API can be made safe if we can guarantee that the rooted struct was created in the runtime that we are using for the `StructRef`. That could also be achieved by storing a "unique identifier" that matches that of a runtime.

**Comment by baszalmstra** [comment]
I modified the API the remove the need for `Rc<RefCell<..>>` in #370 , this makes the `Runtime` `Send` which should make it more friendly in a threaded/async environment.
