### ISSUE TITLE
Mun 0.3 depends on VS 2019 redist on Windows

### ISSUE THREAD

**Issue by codec-abc** [mun-lang/mun#322]
Hi,

Mun newbie here. I wanted to test the 0.3 on Windows but it seems there is a bug with it. Here What I did:

1. I downloaded mun 0.3 for Windows using Github releases
2. Unzipped ``mun.exe`` into a new directory on my desktop
3. Opened a terminal into this directory and typed ``mun new mun-test``
4. Program ran but no file nor directory were created
5. Run ``mun --help``. Nothing happened

Then I downloaded the 0.2.1 version and the ``mun --help`` command printed something in the console. So my guess is that something is broken on 0.3. Let me know if I can help fix this.

**Comment by Ivo-Balbaert** [comment]
I'm also a Mun newbie, but I downloaded Mun v0.3 today and follow the same steps as above on Windows 10 Home 20H2 19042.867, 64 bit. Every step above works for me.
Is your Windows OS also 64 bit?

**Comment by codec-abc** [comment]
Yes, Windows 10 Professional 64 bits. But this is my work computer with a lot of corporate software on it that might interfere with mun. Yet I find surprising that even  ``mun --help`` print nothing. Does it work on yours with the 0.3 version?

**Comment by Ivo-Balbaert** [comment]
This is the display of mun --help on my system:

C:\Users\ivoba>mun --help
mun 0.3.0
The Mun Project Developers
The Mun executable enables compiling and running standalone Mun code

USAGE:
    mun <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    build              Compiles a local Mun file into a module
    help               Prints this message or the help of the given subcommand(s)
    init
    language-server
    new
    start

**Comment by codec-abc** [comment]
Thanks, like I said in the edited section for my previous message, it appears to be a msvc runtime issue. Installing the 2019 should hopefully fix this. I can probably close the issue but I wonder if it is worth mentioning that Mun prebuild binaries depend on the 2019 redistributable.


Maintainers of Mun, do you think it is worthy to be said on the Readme?

**Comment by Wodann** [comment]
Thanks for reporting this. We'll update the readme and see whether we can remove the dependency in the future

**Comment by circutrider21** [comment]
If you guys want to get rid of the VS2019 Reditributable dependency, then compile for the x86_64-pc-windows-gnu target instead of msvc. The x86_64-pc-windows-gnu target is statically linked, therefore having no dynamic/runtime dependencies.

**Comment by baszalmstra** [comment]
For Rust crates that could solve the problem but we also have to build LLVM like that.

**Comment by baszalmstra** [comment]
Another option would be to simply static link the crt: https://reddit.com/r/rust/comments/ekts0d/how_to_link_crt_statically_when_building_with_msvc/

**Comment by baszalmstra** [comment]
Doing a bit of research led me to: 

> LLVM_USE_CRT_{target}:STRING
> On Windows, tells which version of the C runtime library (CRT) should be used. For example, -DLLVM_USE_CRT_RELEASE=MT would statically link the CRT into the LLVM tools and library.

https://llvm.org/docs/CMake.html

**Comment by baszalmstra** [comment]
I took a stab at it and got it working. It took me some time to build LLVM with a static CRT. I am currently uploading the LLVM binaries targeting the static CRT to the original 12.0.1 release we maintain.
