### ISSUE TITLE
Type alias visibility & leaking

### ISSUE THREAD

**Issue by mkhan45** [mun-lang/mun#339]
In Rust, private type aliases can still be used in public function signatures so long as the type they represent is public:

```rs
type Foo = usize;

// usize is public, so this is perfectly valid
pub fn foo() -> Foo {
    1
}

fn main() {
    println!("{}", foo());
}
```

With #338, this behavior is the same in Mun, but we may want to change it so that we would get a "can't leak private type" error.

**Comment by Wodann** [comment]
See crates/mun_hir/src/expr/validator/snapshots/mun_hir__expr__validator__tests__private_leak_alias.snap

**Comment by Wodann** [comment]
@baszalmstra This raises the question of how we should deal with type aliases. Are they interpreted as:

**1. a weak type**
The type at the end of a chain of type aliases:

```rust
type A = B;
type B = i32

fn foo() -> A { -2 }
```

becomes `fn foo() -> i32`.

The type alias' visibility modifier overwrites the visibility of the aliased type.

**2. a strong type**
The type alias itself is a type:

```rust
type A = i32;

fn foo() -> A { -2 }
```

remains its function signature. 

The type alias' visibility modifier applies to the type alias alone.

A type alias will throw a validator error if its own visibility is "more" than that of the type it aliases:
```rust
type A = i32;
pub type B = A; // can't leak private type A
```

The aliased type is implicitly cast to the type alias type:
```rust
type A = i32;
fn foo() -> A {
  -2 // casts i32 to A
}
```

This raises the question whether we can derive the type of a literal when using type aliases?
