### ISSUE TITLE
Reusing mun_lld

### ISSUE THREAD

**Issue by ghaith** [mun-lang/mun#353]
Hello,
I recently started using the mun_lld crate for linking in our compiler [RuSTy](https://github.com/PLC-lang/rusty) and I find it very useful on its own.
Would you be open to separating this crate from the mun language so it could be easily reused/extended from external projects?
I would like, for example, to add LLVM12 support but this is currently blocked by mun supporting it.

Thank you

**Comment by baszalmstra** [comment]
Sorry for the terribly late response!

We would definitely be open to it but it is not something on our priority list. The LLD API is very limited and used to contain a lot of bugs with multiple invocations and threading, we created the mun_lld crate to fit our specific use-case. If this is already generic enough then please do go ahead. We would be glad to adopt it as well!

**Comment by ghaith** [comment]
Hello,

Thank you for the reply, I would still be interested in collaborating here.
In our compiler we only use the linux section of the linker at the moment, and the code already available in the crate has proved sufficient.
I have since forked the crate into https://github.com/ghaith/lld-rs 
I would be happy to hand it over to the mun project and reuse it from there.

**Comment by baszalmstra** [comment]
That sounds great! We can add the lld-rs repository to the mun-lang organization and use that too, if thats what you are suggesting?

**Comment by ghaith** [comment]
I can't seem to transfer the repository since I don't have access.
But since the issues/PRs are practically still empty you could probably just fork it into the mun-lang community.
I'll then probably archive my version and redirect our project to mun-lang's version (Or to the crate if you upload one)

**Comment by baszalmstra** [comment]
[lld_rs](https://crates.io/crates/lld_rs) is now a standalone crate that already supports LLVM13. Thanks, @ghaith for everything you did!
