### ISSUE TITLE
Provide suggestions if a function cannot be found

### ISSUE THREAD

**Issue by baszalmstra** [mun-lang/mun#412]
If a mun function cannot be found when trying to execute some Mun code via the runtime, include suggestions of correct function names. 

**Current Behaviour**

https://github.com/mun-lang/mun/blob/cc839c3ce7727834b7b395ba8f0c2100d859b355/crates/mun_runtime/tests/functions.rs#L6-L28

**Desired behavour**
The returned error message contains an additional line recommending the function name/path that's the closest match, something like: 

```
help: there is a function with a similar name: `main`
```

**Good first issue process:**

- [x] [read our contributing guidelines](https://github.com/mun-lang/mun/blob/master/CONTRIBUTING.md)
  - You can fork [this branch](https://github.com/mun-lang/mun/tree/improvement/function-suggestions), which already contains a test to help you get started
- [x] claim this issue (assign yourself or comment below)
- [ ] implement the feature and start a Pull Request with in the description: closes #412.

If this is your first PR, welcome 🎉 😄

**Comment by belagoesr** [comment]
I'll be taking this one!
