### ISSUE TITLE
Support for iOS

### ISSUE THREAD

**Issue by aghoneim92** [mun-lang/mun#417]
I would like to build a `munlib` for iOS. I have tinkered with the code in `mun_target` and added an ios target, and call mun with `--target x86_64-apple-ios`. Still, the generated lib file is for macOS. Any help with the parts that I need to change?

**Comment by aghoneim92** [comment]
Sure, here's the code for it:
```rust
// apple_base.rs

fn ios_deployment_target() -> (u32, u32) {
    let deployment_target = env::var("IOS_DEPLOYMENT_TARGET").ok();
    let version = deployment_target
        .as_ref()
        .and_then(|s| s.split_once('.'))
        .and_then(|(a, b)| {
            a.parse::<u32>()
                .and_then(|a| b.parse::<u32>().map(|b| (a, b)))
                .ok()
        });

    version.unwrap_or((15, 5))
}
```
```rust
// crates/mun_target/src/spec/x86_64_apple_ios.rs

use crate::spec::{LinkerFlavor, Target, TargetResult};

pub fn target() -> TargetResult {
    let base = super::apple_base::opts();
    // base.cpu = "core2".to_string();

    // Clang automatically chooses a more specific target based on
    // MACOSX_DEPLOYMENT_TARGET.  To enable cross-language LTO to work
    // correctly, we do too.
    let arch = "x86_64";
    let llvm_target = super::apple_base::ios_llvm_target(arch);

    Ok(Target {
        llvm_target,
        target_os: "ios".to_string(),
        target_endian: "little".to_string(),
        target_pointer_width: "64".to_string(),
        target_c_int_width: "32".to_string(),
        target_env: String::new(),
        target_vendor: "apple".to_string(),
        arch: arch.to_string(),
        data_layout: "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
            .to_string(),
        linker_flavor: LinkerFlavor::Ld64,
        options: base,
    })
}
```

**Comment by aghoneim92** [comment]
One thing I noted is that in `mun_codegen` the `get_apple_sdk_root` function gets the macOS sdk root by default, so I set `IPHONEOS_DEPLOYMENT_TARGET=15.5 SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk`

**Comment by baszalmstra** [comment]
Im booting ye old mac, Ill see if I can get something working.

**Comment by baszalmstra** [comment]
I threw something together to at least get things compiling: https://github.com/baszalmstra/mun/tree/feat/ios

You should be able to build binaries for IOS and for IOS simulator with:

```bash
mun build ... --target aarch64_apple_ios
# OR
mun build ... --target aarch64_apple_ios_sim
```

However, I have no idea whether or not you can get the runtime to compile for IOS as well. @aghoneim92 Did you already get that working?

**Comment by aghoneim92** [comment]
This is awesome! And so much work, I really appreciate you taking the time. By the way, is there a specific reason why you defined the targets with underscore separators instead of hyphens?
I still haven't gotten to the runtime, but so far I've added it to my project's `Cargo.toml` and running `cargo build` with an ios target doesn't fail so I'm crossing my fingers that it'll "just work"

**Comment by aghoneim92** [comment]
It worked! I was able to output pi from mun :) This is really exciting. I'm making a flutter-like project where mun would be the main language for developing client-side logic. One problem I faced was that using the latest release of the mun runtime threw an error somewhere in `AssemblyInfo`, but using the latest git version works just fine.


> Do note though that I don't think will pass App store restrictions because dynamic loading of shared objects is not allowed. It will work for development though, which is the most important thing. I think in the future it can also be possible to statically link your munlib and the runtime which would be legal in the App store.

Running it in development will definitely do for now, my project is still in its very early stages 😄

**Comment by aghoneim92** [comment]
Now that we have everything working, is there any way I can help get the amazing code you added merged?

**Comment by Wodann** [comment]
> Now that we have everything working, is there any way I can help get the amazing code you added merged? 

Thanks for offering. @baszalmstra will likely create a PR for his changes soon (it's past midnight for him), so we should be covered there.

What would be very helpful is if you could add a chapter to the Mun book detailing how you setup and run a basic hot reloading scenario on iOS (simulator), similar to chapter [1.3](https://docs.mun-lang.org/ch01-03-hello-hot-reloading.html).

**Comment by baszalmstra** [comment]
> @Wodann as far as I know, hot reloading would require a complicated setup, as there isn't any mechanism for the ios simulator to directly access a file on the Mac. Do you have any ideas? Or would a normal example without hot reloading suffice?

Im not sure actually, when I tried it yesterday I just hardcoded the path to the munlib directory and that worked just fine. But that wont work on an actual iDevice ofc, which would be truly awesome.

**Comment by aghoneim92** [comment]
> Im not sure actually, when I tried it yesterday I just hardcoded the path to the munlib directory and that worked just fine. But that wont work on an actual iDevice ofc, which would be truly awesome.

Whoa, that actually works! Okay, I will prepare a guide today 🤓
