### ISSUE TITLE
Integrate annotate-snippets crate

### ISSUE THREAD

**Issue by Wodann** [mun-lang/mun#50]
- [x] claim this issue (assign yourself or comment below)
- [x] [setup repository on your local machine](https://github.com/mun-lang/mun) and make sure all tests pass (`cargo test`)
- [x] read our [contributing guidelines](https://github.com/mun-lang/mun/blob/master/CONTRIBUTING.md)
- [ ] add conversion of [`Diagnostic`](https://github.com/mun-lang/mun/blob/10909c9cca998279686a71ae05b6d284f9413f08/crates/mun_hir/src/diagnostics.rs) instances to annotated snippets using this [crate](https://crates.io/crates/annotate-snippets).
- [ ] start a Pull Request. Set description to `closes #50`. If this is your first PR, welcome :tada: :smile:

**Comment by legendiguess** [comment]
I would like to contribute to this issue :eyes:

**Comment by baszalmstra** [comment]
Implemented in #91 , thanks!
