### ISSUE TITLE
Test whether mun_compiler generated strings are valid UTF-8

### ISSUE THREAD

**Issue by Wodann** [mun-lang/mun#52]
- [x] claim this issue (assign yourself or comment below)
- [ ] [setup repository on your local machine](https://github.com/mun-lang/mun) and make sure all tests pass (`cargo test`)
- [ ] read our [contributing guidelines](https://github.com/mun-lang/mun/blob/master/CONTRIBUTING.md)
- [ ] the Mun Compiler [generates UTF-8 strings](https://github.com/mun-lang/mun/blob/master/crates/mun_codegen/src/code_gen/symbols.rs) in the Mun ABI. For every such function, add a test that check that the resulting shared library contains valid UTF-8.
- [ ] start a Pull Request. Set description to `closes #52`. If this is your first PR, welcome :tada: :smile:

**Comment by legendiguess** [comment]
I would like to contribute to this issue :eyes:
