### ISSUE TITLE
Replace CStr::from_ptr(ptr).to_str() occurences with str::from_utf8_unchecked calls

### ISSUE THREAD

**Issue by Wodann** [mun-lang/mun#53]
**Depends on #52.**

- [x] claim this issue (assign yourself or comment below)
- [x] [setup repository on your local machine](https://github.com/mun-lang/mun) and make sure all tests pass (`cargo test`)
- [x] read our [contributing guidelines](https://github.com/mun-lang/mun/blob/master/CONTRIBUTING.md)
- [x] the Mun Runtime reads [UTF-8 strings generated by the Mun compiler](https://github.com/mun-lang/mun/blob/master/crates/mun_codegen/src/code_gen/symbols.rs) in the Mun ABI. For every such function, replace `CStr::from_ptr(ptr).to_str()` occurences with `str::from_utf8_unchecked` calls.
- [x] start a Pull Request. Set description to `closes #53`. If this is your first PR, welcome :tada: :smile:

**Comment by legendiguess** [comment]
I would like to contribute to this issue :eyes:
