### ISSUE TITLE
Design and implement heap-allocated variables

### ISSUE THREAD

**Issue by Wodann** [mun-lang/mun#54]
**This issue requires some collaboration with the core contributors for language design**

- [ ] claim this issue (assign yourself or comment below)
- [ ] [setup repository on your local machine](https://github.com/mun-lang/mun) and make sure all tests pass (`cargo test`)
- [ ] read our [contributing guidelines](https://github.com/mun-lang/mun/blob/master/CONTRIBUTING.md)
- [ ] propose a language construct for heap-allocated variables ([join Discord](https://discord.gg/SfvvcCU) and post in the #development channel and comment below). For inspiration have a look at Rust's [`Box`](https://doc.rust-lang.org/std/boxed/struct.Box.html).
- [ ] improve and conclude your language design based on feedback
- [ ] implement heap-allocated variables
  * [ ] lexing
  * [ ] parsing
  * [ ] type checking
  * [ ] code generation
  * [ ] ABI
  * [ ] Hot reloading
- [ ] start a Pull Request. Set description to `closes #54`. If this is your first PR, welcome :tada: :smile:

**Comment by baszalmstra** [comment]
Closing since the core developers are working on this.
