### ISSUE TITLE
Missing Cargo.lock

### ISSUE THREAD

**Issue by Samuel-Bowden** [mun-lang/mun#562]
Hello, I have been working on writing a Nix derivation for this project with the aim of compiling and installing Mun on NixOS, and I've noticed that the workspace does not include a Cargo.lock file, which is required to create a deterministic derivation.

I am unsure if the absence of Cargo.lock is intentional or an oversight. Should we consider adding a Cargo.lock to the workspace?

**Comment by baszalmstra** [comment]
Mun is both an executable and a library. 

For libraries I tend not to include a lock file. 
But for the executable, it makes sense to have a lock file.

Since a lock-file always applies to all crates in the project lets just add it.
