### ISSUE TITLE
Can't build mun_compiler + mun_runtime

### ISSUE THREAD

**Issue by trsh** [mun-lang/mun#568]
Cargo
```
[package]
name = "ai"
version = "0.1.0"
edition = "2021"

[dependencies]
mun_runtime = "0.4.0"
mun_compiler = "0.4.0"
```

Error:

error: failed to run custom build command for `lld_rs v130.0.0`

But I am on Ubuntu WSL llvm 140. Prefix `LLVM_SYS_140_PREFIX.` is now set correctly

**Comment by trsh** [comment]
Added 130 llvm and it works now with that.

**Comment by baszalmstra** [comment]
v0.4.0 depends on LLD 13 indeed.
