### ISSUE TITLE
any examples for a hello world web server?

### ISSUE THREAD

**Issue by avierr** [mun-lang/mun#74]

**Comment by Wodann** [comment]
As our resources are limited, we are focusing our efforts on a single use case: game development. We believe that WebAssembly is a bridge to easily connects game development to the web, but - as I said earlier - WebAssembly adaptation is not our main priority.

It's also unlikely that we will release a web server example anytime soon, especially as there are already a lot of good hot reloading resources for the web in other languages. E.g. for Rust, check out [cargo-web](https://github.com/koute/cargo-web).

We do currently have some general-purpose example code for embedding Mun in [Rust](https://github.com/mun-lang/mun/tree/master/crates/mun_runtime/examples) and [C++](https://github.com/mun-lang/example-cpp).
